"""changelengthadparent

Revision ID: 7469029dbe2f
Revises: 2b4c6fce86f5
Create Date: 2018-03-29 16:53:59.293502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7469029dbe2f'
down_revision = '2b4c6fce86f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('ParentHistory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'ParentHistory')
    # ### end Alembic commands ###
